version: '3'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - db_network
      - nc_network

  redis:
    image: redis:alpine
    networks:
      - nc_network

  app:
    image: nextcloud:apache
    #restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - nc_network

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy:/etc/nginx/conf.d
    networks:
      - nc_network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    env_file:
      - db.env
    expose:
      - 80
    networks:
      - nc_network
      - db_network

volumes:
  db:
  nextcloud:

networks:
  nc_network:
  db_network:
