version: '3'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - db_network
      - nc_network

  redis:
    image: redis:alpine
    networks:
      - nc_network

  app:
    image: nextcloud:apache
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - nc_network

  sftp:
    image: atmoz/sftp
    volumes:
      - ${SFTP_MOUNT}:${SFTP_HOME}/download
      - ${SFTP_RSA_PUB}:${SFTP_HOME}/.ssh/keys/id_rsa.pub:ro
    command: ${SFTP_USER}:${SFTP_PASSWORD}:1001
    env_file:
      - .env
    networks:
      nc_network:
        ipv4_address: 10.0.0.7

  nginx:
    image: nginx:alpine
    expose:
      - 80
      - 443
    volumes:
      - ./proxy:/etc/nginx/conf.d
    networks:
      - nc_network

volumes:
  db:
  nextcloud:

networks:
  nc_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
